version: '3.1'
services:
  db:
    image: postgres
    hostname: postgres
    restart: always
    volumes:
      - './pg/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledge_map
    ports:
      - '5432:5432'